'''
  UFF - Universidade Federal Fluminense
  IC - Instituto de Computação
  Curso: Mestrado em Computação
  Aluno: Reinaldo Viana Alvares - ralvares@ic.uff.br
  Última alteração: 26/01/2005

  Adaptação para Python
  06/07/2017
  Larissa Barra Conde
  Engenharia de Computação
  CEFET-MG
'''

import unicodedata

class Afixo:
    afixo = ''
    excecoes = list()

    def __init__(self, afixo, excecoes):
        self.afixo = afixo
        self.excecoes = excecoes

class Prefixo(Afixo):
    def __repr__(self):
        return 'Prefixo: ' + self.afixo

class Sufixo(Afixo):
    minStem = 0

    def __init__(self, afixo, excecoes, minStem):
        Afixo.__init__(self, afixo, excecoes)
        self.minStem = minStem

    def __repr__(self):
        return 'Sufixo: ' + self.afixo

prefixos = list()
sufixos = {}

def initPrefixos():
    prefixos.append(Prefixo('contra', ['contrari','contrat','contrabaix','contraç','contraí','contrai','contrast','contraband','contrai','contracen','contrap']))
    prefixos.append(Prefixo('inter', ['interpre','interi','interp','interv','interess','interced','interdi','interne','interv','intercep']))
    prefixos.append(Prefixo('super', ['supera','supervi','superior','superan','supere','superad','superaç','superá']))
    prefixos.append(Prefixo('trans', ['transfor','transa','transgr','transp','transit','transfer']))
    prefixos.append(Prefixo('ciclo', ['ciclon','cicload','ciclomot']))
    prefixos.append(Prefixo('extra', ['extrat','extrapor','extraç','extrai','extraí']))
    prefixos.append(Prefixo('entre', ['entrecan','entrech','entrev','entret','entreg']))
    prefixos.append(Prefixo('intra', ['intramu']))
    prefixos.append(Prefixo('sobre', ['sobrean','sobrecin','sobrecop','sobrec','sobrefac','sobreir','sobrepuj']))
    prefixos.append(Prefixo('hidro', ['hidrog','hidrol']))
    prefixos.append(Prefixo('semi', ['semin','semicapr','semicarbazi','semichas']))
    prefixos.append(Prefixo('ante', ['antecip','anten','anteri','anteced']))
    prefixos.append(Prefixo('mega', ['megal']))
    prefixos.append(Prefixo('auto', ['autom', 'autor']))
    prefixos.append(Prefixo('mono', ['monócito','monóxilo']))
    prefixos.append(Prefixo('pos', ['posic','posiç','posar','posit','poss','post']))
    prefixos.append(Prefixo('sub', ['substitu','subi','suba','subacada','subaien','subala','subli']))
    prefixos.append(Prefixo('des', ['desafor','desaf','desab','descobr','desej','desmai','desencad','desenvol','desastr','desencant','descart','descri','destin','destil','desesper','desert']))
    prefixos.append(Prefixo('bio', ['biol','biog','biosfera','bioafin','biocida','biótipo']))
    prefixos.append(Prefixo('bis', ['bisc','bisab','bisbilh','bisc','bisna','bisp','bist']))
    prefixos.append(Prefixo('epi', ['epistemol','epicli','epidem','epilep']))
    prefixos.append(Prefixo('im', ['imag']))
    prefixos.append(Prefixo('en', ['encolh','enxer','enge','englo','enve','envi','encen','encerr','ench','encontr','enga','enla','ensin','enxa','ent','end','enf','enj','enaip','enaç','enalt','enamor','encar','encad','encab']))
    prefixos.append(Prefixo('in', ['interpr','interg','intere','industr','inform','intern','infiltr','incub','inspir','indu�','induz','index','invo','interce','intest','intim','instal','instan','instr','inscr','inten','invad','invas','insi','inund','inaug','inch','incr','incid','incl','increment','indag','inedi','ingres','inici','investig','intrig','inven','insti','integr','insult','invest','intri','inclusiv','inform','interes','intrag','individ','industr','inspir']))
    prefixos.append(Prefixo('bi', ['bisc','biol','biograf','bilh','bic','biq','bich','bigo','bia','biaba','biafrense','bialad','bianda','biaxia','bibelot','bibli','bibliocle','bibliograf','bibliotec','bibliol','biquíni']))

def initSufixos():
    sufixosS = list()
    sufixosS.append(Sufixo('abilíssimas', [], 4))
    sufixosS.append(Sufixo('abilíssimos', [], 4))
    sufixosS.append(Sufixo('icitários', ['publicitários'], 4))
    sufixosS.append(Sufixo('icitárias', ['publicitárias'], 4))
    sufixosS.append(Sufixo('oavantes', [], 4))
    sufixosS.append(Sufixo('alizadas', ['hospitalizadas'], 3))
    sufixosS.append(Sufixo('alizados', ['hospitalizados'], 3))
    sufixosS.append(Sufixo('ológicos', [], 4))
    sufixosS.append(Sufixo('amentos', [], 4))
    sufixosS.append(Sufixo('atórios', [], 4))
    sufixosS.append(Sufixo('atórias', [], 4))
    sufixosS.append(Sufixo('ísticos', [], 3))
    sufixosS.append(Sufixo('itários', [], 4))
    sufixosS.append(Sufixo('itárias', [], 4))
    sufixosS.append(Sufixo('izinhos', [], 4))
    sufixosS.append(Sufixo('adoras', [], 4))
    sufixosS.append(Sufixo('adores', [], 4))
    sufixosS.append(Sufixo('aremos', [], 4))
    sufixosS.append(Sufixo('aríeis', [], 2))
    sufixosS.append(Sufixo('ásseis', [], 2))
    sufixosS.append(Sufixo('ativas', ['alternativas'], 3))
    sufixosS.append(Sufixo('ativos', ['alternativos'], 3))
    sufixosS.append(Sufixo('edoras', [], 2))
    sufixosS.append(Sufixo('eríeis', [], 3))
    sufixosS.append(Sufixo('êsseis', [], 3))
    sufixosS.append(Sufixo('gastes', [], 5))
    sufixosS.append(Sufixo('idades', [], 4))
    sufixosS.append(Sufixo('iríeis', [], 3))
    sufixosS.append(Sufixo('ísseis', [], 3))
    sufixosS.append(Sufixo('izadas', [], 4))
    sufixosS.append(Sufixo('ólitos', [], 3))
    sufixosS.append(Sufixo('ólitas', [], 3))
    sufixosS.append(Sufixo('antes', [], 4))
    sufixosS.append(Sufixo('areis', [], 2))
    sufixosS.append(Sufixo('áreis', [], 3))
    sufixosS.append(Sufixo('astes', [], 3))
    sufixosS.append(Sufixo('áveis', [], 2))
    sufixosS.append(Sufixo('entes', ['acidentes', 'contentes', 'continentes', 'aparentes'], 4))
    sufixosS.append(Sufixo('ereis', [], 3))
    sufixosS.append(Sufixo('êreis', [], 3))
    sufixosS.append(Sufixo('agens', [], 4))
    sufixosS.append(Sufixo('inhas', [], 4))
    sufixosS.append(Sufixo('ireis', ['admireis'], 3))
    sufixosS.append(Sufixo('istas', [], 3))
    sufixosS.append(Sufixo('íveis', [], 2))
    sufixosS.append(Sufixo('adas', ['formalizadas'], 3))
    sufixosS.append(Sufixo('ados', ['formalizados', 'consulados'], 3))
    sufixosS.append(Sufixo('íeis', [], 3))
    sufixosS.append(Sufixo('idas', ['compridas'], 3))
    sufixosS.append(Sufixo('osos', [], 3))
    sufixosS.append(Sufixo('osas', [], 3))
    sufixosS.append(Sufixo('ueis', [], 3))
    sufixosS.append(Sufixo('ães', ['mães', 'cães', 'pães'], 1))
    sufixosS.append(Sufixo('ais', ['casais', 'mais'], 1))
    sufixosS.append(Sufixo('ces', [], 4))
    sufixosS.append(Sufixo('eis', ['acheis', 'alopreis', 'abafeis', 'tendeis', 'rimeis'], 2))
    sufixosS.append(Sufixo('éis', [], 2))
    sufixosS.append(Sufixo('les', [], 3))
    sufixosS.append(Sufixo('ões', [], 3))
    sufixosS.append(Sufixo('óis', [], 2))
    sufixosS.append(Sufixo('res', [], 3))
    sufixosS.append(Sufixo('as', [], 4))
    sufixosS.append(Sufixo('ás', [], 4))
    sufixosS.append(Sufixo('ês', [], 4))
    sufixosS.append(Sufixo('es', [], 3))
    sufixosS.append(Sufixo('is', ['leis', 'lápis', 'cais', 'mais', 'crúcis', 'biquínis', 'pois', 'depois', 'dois'], 2))
    sufixosS.append(Sufixo('ns', ['parabéns'], 1))
    sufixosS.append(Sufixo('s', ['parabéns','aliás','pires','lápis','cais','mais', 'férias','fezes','pêsames','crúcis','gás', 'atrás','moisés','através','convés','ês','país','após','ambas','ambos','messias','ananás'], 2))
    sufixos['s'] = sufixosS

    sufixosR = list()
    sufixosR.append(Sufixo('izador', [], 4))
    sufixosR.append(Sufixo('ecedor', [], 4))
    sufixosR.append(Sufixo('essor', ['professor'], 4))
    sufixosR.append(Sufixo('ionar', [], 5))
    sufixosR.append(Sufixo('tizar', ['alfabetizar', 'amortizar'], 4))
    sufixosR.append(Sufixo('tedor', ['prometedor'], 4))
    sufixosR.append(Sufixo('ador', ['mercador'], 3))
    sufixosR.append(Sufixo('edor', [], 3))
    sufixosR.append(Sufixo('idor', ['ouvidor'], 4))
    sufixosR.append(Sufixo('itar', ['apriveitar', 'acreditar', 'explicitar', 'estreitar'], 5))
    sufixosR.append(Sufixo('izar', ['amortizar', 'organizar'], 5))
    sufixosR.append(Sufixo('dor', ['armador', 'ouvidor'], 4))
    sufixosR.append(Sufixo('ear', ['alardear', 'nuclear'], 4))
    sufixosR.append(Sufixo('iar', [], 3))
    sufixosR.append(Sufixo('sor', ['assessor'], 4))
    sufixosR.append(Sufixo('tor', ['reitor','monitor','benfeitor','leitor','editor','pastor','produtor','promotor','consultor'], 3))
    sufixosR.append(Sufixo('ar', ['repar','alar','ácar','dispar','compar','ampar','apar','encar','azar','bazar','patamar'], 2))
    sufixosR.append(Sufixo('ár', [], 2))
    sufixosR.append(Sufixo('er', ['ader','coer','toler','sincer','esper','vener','liber','refer','oper','super','aglomer','oner','quer'], 2))
    sufixosR.append(Sufixo('ir', ['cheir', 'freir', 'inspir'], 3))
    sufixosR.append(Sufixo('or', ['terror','escor','humor','namor','decor','amor','condecor','explor','comemor','monitor','chor','mármor','melhor','pior','valor','ador','motor','melhor','redor','rigor','sensor','tambor','tumor','assessor','benfeitor','pastor','terior','favor','autor'], 2))
    sufixos['r'] = sufixosR

    sufixosM = list()
    sufixosM.append(Sufixo('oriaram', [], 4))
    sufixosM.append(Sufixo('bilizaram', [], 4))
    sufixosM.append(Sufixo('ariam', [], 2))
    sufixosM.append(Sufixo('assem', [], 2))
    sufixosM.append(Sufixo('eriam', [], 3))
    sufixosM.append(Sufixo('essem', [], 3))
    sufixosM.append(Sufixo('iriam', [], 3))
    sufixosM.append(Sufixo('issem', [], 3))
    sufixosM.append(Sufixo('caram', [], 4))
    sufixosM.append(Sufixo('agem', ['coragem', 'chantagem', 'vantagem', 'carruagem'], 3))
    sufixosM.append(Sufixo('aram', [], 2))
    sufixosM.append(Sufixo('arem', [], 2))
    sufixosM.append(Sufixo('avam', ['agravam'], 2))
    sufixosM.append(Sufixo('eram', [], 3))
    sufixosM.append(Sufixo('erem', [], 3))
    sufixosM.append(Sufixo('íram', [], 3))
    sufixosM.append(Sufixo('iram', [], 3))
    sufixosM.append(Sufixo('irem', ['adquirem'], 3))
    sufixosM.append(Sufixo('iam', ['enfiam', 'ampliam', 'elogiam', 'ensaiam'], 3))
    sufixosM.append(Sufixo('am', [], 4))
    sufixosM.append(Sufixo('em', ['trem', 'grem', 'crem', 'suprem', 'extrem', 'esprem', 'alem', 'virgem'], 2))
    sufixos['m'] = sufixosM

    sufixosL = list()
    sufixosL.append(Sufixo('alizável', [], 4))
    sufixosL.append(Sufixo('ionável', [], 4))
    sufixosL.append(Sufixo('acional', [], 4))
    sufixosL.append(Sufixo('encial', [], 5))
    sufixosL.append(Sufixo('ional', [], 4))
    sufixosL.append(Sufixo('cável', [], 4))
    sufixosL.append(Sufixo('ábil', [], 3))
    sufixosL.append(Sufixo('ável', ['afável', 'razoável', 'potável', 'vulnerável'], 2))
    sufixosL.append(Sufixo('ical', [], 3))
    sufixosL.append(Sufixo('inal', [], 3))
    sufixosL.append(Sufixo('ivel', [], 3))
    sufixosL.append(Sufixo('ível', ['possível'], 3))
    sufixosL.append(Sufixo('tural', [], 4))
    sufixosL.append(Sufixo('ural', [], 4))
    sufixosL.append(Sufixo('bil', [], 3))
    sufixosL.append(Sufixo('ial', [], 3))
    sufixosL.append(Sufixo('uel', [], 4))
    sufixosL.append(Sufixo('ual', ['manual', 'bissexual', 'virtual', 'visual', 'pontual'], 3))
    sufixosL.append(Sufixo('vel', ['possível', 'vulnerável', 'solúvel'], 5))
    sufixosL.append(Sufixo('al', ['formal', 'manual', 'castanhal', 'catedral', 'afinal', 'animal', 'estatal', 'bissexual', 'desleal', 'fiscal', 'formal', 'liberal', 'postal', 'virtual', 'visual', 'pontual', 'sideral', 'sucursal'], 4))
    sufixosL.append(Sufixo('il', [], 4))
    sufixos['l'] = sufixosL

    sufixosO = list()
    sufixosO.append(Sufixo('abilíssimo', [], 5))
    sufixosO.append(Sufixo('antíssimo', [], 4))
    sufixosO.append(Sufixo('adíssimo', [], 4))
    sufixosO.append(Sufixo('alístico', [], 3))
    sufixosO.append(Sufixo('omaníaco', [], 3))
    sufixosO.append(Sufixo('alizado', [], 4))
    sufixosO.append(Sufixo('atizado', [], 4))
    sufixosO.append(Sufixo('díssimo', [], 5))
    sufixosO.append(Sufixo('eirismo', [], 4))
    sufixosO.append(Sufixo('iamento', [], 4))
    sufixosO.append(Sufixo('adeiro', ['desfiladeiro'], 4))
    sufixosO.append(Sufixo('adinho', [], 3))
    sufixosO.append(Sufixo('alismo', [], 4))
    sufixosO.append(Sufixo('amento', ['firmamento', 'fundamento', 'departamento'], 3))
    sufixosO.append(Sufixo('aríamo', [], 2))
    sufixosO.append(Sufixo('ássemo', [], 2))
    sufixosO.append(Sufixo('ástico', ['eclesiástico'], 4))
    sufixosO.append(Sufixo('atário', [], 2))
    sufixosO.append(Sufixo('atício', [], 4))
    sufixosO.append(Sufixo('atório', [], 3))
    sufixosO.append(Sufixo('áutico', [], 4))
    sufixosO.append(Sufixo('edouro', [], 3))
    sufixosO.append(Sufixo('eríamo', [], 2))
    sufixosO.append(Sufixo('érrimo', [], 4))
    sufixosO.append(Sufixo('êssemo', [], 2))
    sufixosO.append(Sufixo('êutico', [], 4))
    sufixosO.append(Sufixo('imento', [], 3))
    sufixosO.append(Sufixo('iríamo', [], 3))
    sufixosO.append(Sufixo('íssemo', [], 3))
    sufixosO.append(Sufixo('íssimo', [], 3))
    sufixosO.append(Sufixo('ivismo', [], 4))
    sufixosO.append(Sufixo('ização', [], 4))
    sufixosO.append(Sufixo('queiro', [], 3))
    sufixosO.append(Sufixo('quinho', [], 4))
    sufixosO.append(Sufixo('tizado', ['alfabetizado'], 4))
    sufixosO.append(Sufixo('zarrão', [], 3))
    sufixosO.append(Sufixo('alhão', [], 4))
    sufixosO.append(Sufixo('áramo', [], 2))
    sufixosO.append(Sufixo('aremo', [], 2))
    sufixosO.append(Sufixo('arrão', [], 4))
    sufixosO.append(Sufixo('ativo', ['pejorativo', 'relativo'], 4))
    sufixosO.append(Sufixo('ávamo', [], 2))
    sufixosO.append(Sufixo('êramo', [], 3))
    sufixosO.append(Sufixo('eremo', [], 3))
    sufixosO.append(Sufixo('ésimo', [], 3))
    sufixosO.append(Sufixo('íramo', [], 3))
    sufixosO.append(Sufixo('iremo', [], 3))
    sufixosO.append(Sufixo('izado', ['organizado', 'pulverizado'], 5))
    sufixosO.append(Sufixo('mento', ['firmamento', 'elemento', 'complemento', 'instrumento', 'departamento'], 6))
    sufixosO.append(Sufixo('ólogo', [], 4))
    sufixosO.append(Sufixo('uinho', [], 4))
    sufixosO.append(Sufixo('zinho', [], 2))
    sufixosO.append(Sufixo('ação', [], 3))
    sufixosO.append(Sufixo('acho', [], 2))
    sufixosO.append(Sufixo('adão', [], 4))
    sufixosO.append(Sufixo('ando', [], 2))
    sufixosO.append(Sufixo('arão', [], 2))
    sufixosO.append(Sufixo('ário', ['voluntário', 'salário', 'aniversário', 'diário', 'lionário', 'funcionário', 'armário'], 3))
    sufixosO.append(Sufixo('armo', [], 2))
    sufixosO.append(Sufixo('ázio', ['topázio'], 3))
    sufixosO.append(Sufixo('eiro', ['desfiladeiro', 'pioneiro', 'mosteiro'], 3))
    sufixosO.append(Sufixo('endo', ['pretendo'], 3))
    sufixosO.append(Sufixo('erão', [], 3))
    sufixosO.append(Sufixo('ério', [], 6))
    sufixosO.append(Sufixo('ermo', [], 3))
    sufixosO.append(Sufixo('esco', [], 4))
    sufixosO.append(Sufixo('íaco', [], 3))
    sufixosO.append(Sufixo('íamo', [], 3))
    sufixosO.append(Sufixo('ício', [], 4))
    sufixosO.append(Sufixo('idão', [], 4))
    sufixosO.append(Sufixo('indo', ['falindo'], 3))
    sufixosO.append(Sufixo('inho', ['caminho', 'cominho', 'carinho', 'adivinho'], 3))
    sufixosO.append(Sufixo('irão', [], 2))
    sufixosO.append(Sufixo('irmo', [], 3))
    sufixosO.append(Sufixo('ismo', ['cinismo', 'turismo'], 3))
    sufixosO.append(Sufixo('ondo', [], 3))
    sufixosO.append(Sufixo('tico', ['político', 'eclesiástico', 'diagnostico', 'prático', 'doméstico', 'diagnóstico', 'idêntico', 'alopático', 'artístico', 'autêntico', 'eclético', 'crítico', 'critico'], 3))
    sufixosO.append(Sufixo('tivo', ['relativo', 'coletivo'], 4))
    sufixosO.append(Sufixo('uoso', [], 3))
    sufixosO.append(Sufixo('aço', ['antebraço'], 4))
    sufixosO.append(Sufixo('ado', ['grado', 'consulado'], 2))
    sufixosO.append(Sufixo('amo', ['clamo'], 2))
    sufixosO.append(Sufixo('ano', ['veterano'], 4))
    sufixosO.append(Sufixo('ego', [], 3))
    sufixosO.append(Sufixo('emo', [], 2))
    sufixosO.append(Sufixo('ico', ['tico', 'público', 'explico', 'analógico'], 4))
    sufixosO.append(Sufixo('ido', ['apelido', 'cândido', 'consolido', 'rápido', 'decido', 'tímido', 'duvido', 'marido', 'bandido'], 3))
    sufixosO.append(Sufixo('ído', [], 3))
    sufixosO.append(Sufixo('imo', ['reprimo', 'intimo', 'íntimo', 'nimo', 'queimo', 'ximo'], 3))
    sufixosO.append(Sufixo('ivo', ['efetivo', 'passivo', 'possessivo', 'pejorativo', 'positivo'], 4))
    sufixosO.append(Sufixo('omo', [], 3))
    sufixosO.append(Sufixo('oso', ['precioso'], 3))
    sufixosO.append(Sufixo('rio', ['voluntário', 'salário', 'funcionário', 'aniversário', 'diário', 'compulsório', 'lionário', 'próprio', 'stério', 'armário'], 5))
    sufixosO.append(Sufixo('zão', ['coalizão'], 2))
    sufixosO.append(Sufixo('ão', ['camarão', 'chimarrão', 'canção', 'coração', 'embrião', 'grotão', 'glutão', 'ficção', 'fogão', 'feição', 'furacão', 'gamão', 'lampião', 'leão', 'macacão', 'nação', 'órfão', 'orgão', 'patrão', 'portão', 'quinhão', 'rincão', 'tração', 'falcão', 'espião', 'mamão', 'folião', 'cordão', 'aptidão', 'campeão', 'colchão', 'limão', 'leilão', 'melão', 'barão', 'milhão', 'bilhão', 'fusão', 'cristão', 'ilusão', 'capitão', 'estação', 'senão'], 3))
    sufixosO.append(Sufixo('o', ['corro', 'consulado'], 4))
    sufixos['o'] = sufixosO
    sufixos['ó'] = sufixosO
    sufixos['ô'] = sufixosO

    sufixosA = list()
    sufixosA.append(Sufixo('abilíssima', [], 4))
    sufixosA.append(Sufixo('encialista', [], 4))
    sufixosA.append(Sufixo('icionista', [], 4))
    sufixosA.append(Sufixo('anciaria', [], 4))
    sufixosA.append(Sufixo('cionista', [], 5))
    sufixosA.append(Sufixo('alizada', [], 4))
    sufixosA.append(Sufixo('anciava', [], 4))
    sufixosA.append(Sufixo('ericida', [], 4))
    sufixosA.append(Sufixo('ionista', [], 5))
    sufixosA.append(Sufixo('adinha', ['safadinha'], 3))
    sufixosA.append(Sufixo('alista', ['jornalista'], 5))
    sufixosA.append(Sufixo('astica', [], 3))
    sufixosA.append(Sufixo('ástica', [], 3))
    sufixosA.append(Sufixo('atoria', [], 5))
    sufixosA.append(Sufixo('íssima', [], 4))
    sufixosA.append(Sufixo('omania', [], 3))
    sufixosA.append(Sufixo('adora', [], 3))
    sufixosA.append(Sufixo('ância', ['ambulância'], 4))
    sufixosA.append(Sufixo('ência', ['competência'], 3))
    sufixosA.append(Sufixo('izará', [], 4))
    sufixosA.append(Sufixo('aria', [], 2))
    sufixosA.append(Sufixo('arra', [], 3))
    sufixosA.append(Sufixo('auta', [], 5))
    sufixosA.append(Sufixo('cada', [], 4))
    sufixosA.append(Sufixo('cava', [], 4))
    sufixosA.append(Sufixo('eira', ['beira', 'cadeira', 'frigideira', 'bandeira', 'feira', 'capoeira', 'barreira', 'fronteira', 'besteira', 'poeira'], 3))
    sufixosA.append(Sufixo('eria', [], 3))
    sufixosA.append(Sufixo('íaca', [], 3))
    sufixosA.append(Sufixo('iava', ['ampliava', 'espiava'], 4))
    sufixosA.append(Sufixo('inha', ['adiv', 'inho', 'rainha', 'linha', 'minha'], 3))
    sufixosA.append(Sufixo('iona', ['aciona'], 3))
    sufixosA.append(Sufixo('iria', [], 3))
    sufixosA.append(Sufixo('ista', [], 4))
    sufixosA.append(Sufixo('oria', ['categoria'], 4))
    sufixosA.append(Sufixo('aça', [], 4))
    sufixosA.append(Sufixo('ada', ['pitada'], 2))
    sufixosA.append(Sufixo('ara', ['arara', 'prepara'], 2))
    sufixosA.append(Sufixo('ará', ['alvará'], 2))
    sufixosA.append(Sufixo('ava', ['agrava', 'alinhava'], 2))
    sufixosA.append(Sufixo('era', ['acelera', 'espera'], 3))
    sufixosA.append(Sufixo('erá', [], 3))
    sufixosA.append(Sufixo('esa', ['mesa', 'obesa', 'princesa', 'turquesa', 'ilesa', 'pesa', 'presa'], 3))
    sufixosA.append(Sufixo('eza', [], 3))
    sufixosA.append(Sufixo('ica', ['mágica', 'dica', 'analógica'], 3))
    sufixosA.append(Sufixo('ida', ['vida', 'comprida', 'dúvida'], 3))
    sufixosA.append(Sufixo('ída', ['recaída', 'saída'], 3))
    sufixosA.append(Sufixo('ima', ['vítima'], 3))
    sufixosA.append(Sufixo('ira', ['fronteira', 's�tira'], 3))
    sufixosA.append(Sufixo('irá', [], 3))
    sufixosA.append(Sufixo('iva', ['saliva', 'oliva'], 3))
    sufixosA.append(Sufixo('ona', ['aciona', 'iona', 'cortisona', 'monótona', 'maratona', 'acetona', 'detona', 'carona'], 3))
    sufixosA.append(Sufixo('ora', [], 3))
    sufixosA.append(Sufixo('osa', ['mucosa', 'prosa'], 3))
    sufixosA.append(Sufixo('uça', [], 4))
    sufixosA.append(Sufixo('uía', [], 5))
    sufixosA.append(Sufixo('ura', ['imatura', 'acupuntura', 'costura'], 4))
    sufixosA.append(Sufixo('ia', ['estória', 'fatia', 'acia', 'praia', 'elogia', 'mania', 'lábia', 'aprecia', 'polícia', 'arredia', 'cheia', '�sia'], 3))
    sufixosA.append(Sufixo('na', ['aciona', 'clandestina', 'carona', 'abandona', 'lona', 'iona', 'cortisona', 'monótona', 'maratona', 'acetona', 'detona', 'guiana', 'campana', 'grana', 'caravana', 'banana', 'paisana'], 4))
    sufixosA.append(Sufixo('za', ['conduza'], 4))
    sufixosA.append(Sufixo('ã', ['amanhã', 'arapuã', 'fã', 'divã'], 2))
    sufixosA.append(Sufixo('a', ['anima'], 3))
    sufixos['a'] = sufixosA
    sufixos['á'] = sufixosA

    sufixosU = list()
    sufixosU.append(Sufixo('bilizou', ['caracterizou', 'contabilizou'], 4))
    sufixosU.append(Sufixo('izou', ['caracterizou'], 4))
    sufixosU.append(Sufixo('zou', [], 3))
    sufixosU.append(Sufixo('çou', [], 4))
    sufixosU.append(Sufixo('éu', ['chapéu'], 3))
    sufixosU.append(Sufixo('eu', [], 3))
    sufixosU.append(Sufixo('iu', [], 3))
    sufixosU.append(Sufixo('ou', [], 3))
    sufixosU.append(Sufixo('u', ['bambu', 'censu', 'individu', 'acapu'], 4))
    sufixos['u'] = sufixosU
    sufixos['ú'] = sufixosU

    sufixosE = list()
    sufixosE.append(Sufixo('ativamente', [], 5))
    sufixosE.append(Sufixo('nciosidade', [], 3))
    sufixosE.append(Sufixo('abilidade', [], 5))
    sufixosE.append(Sufixo('entemente', [], 5))
    sufixosE.append(Sufixo('adamente', [], 4))
    sufixosE.append(Sufixo('anamente', [], 5))
    sufixosE.append(Sufixo('icamente', [], 5))
    sufixosE.append(Sufixo('idamente', [], 5))
    sufixosE.append(Sufixo('osamente', [], 5))
    sufixosE.append(Sufixo('ariedade', [], 5))
    sufixosE.append(Sufixo('alidade', [], 5))
    sufixosE.append(Sufixo('almente', [], 4))
    sufixosE.append(Sufixo('ióstase', [], 5))
    sufixosE.append(Sufixo('ividade', [], 5))
    sufixosE.append(Sufixo('amente', ['severamente'], 4))
    sufixosE.append(Sufixo('eirice', [], 5))
    sufixosE.append(Sufixo('emente', ['implemente'], 4))
    sufixosE.append(Sufixo('eriose', [], 4))
    sufixosE.append(Sufixo('iólise', [], 5))
    sufixosE.append(Sufixo('izante', [], 5))
    sufixosE.append(Sufixo('itante', ['visitante'], 4))
    sufixosE.append(Sufixo('arete', [], 4))
    sufixosE.append(Sufixo('atite', [], 4))
    sufixosE.append(Sufixo('idade', ['autoridade', 'comunidade'], 3))
    sufixosE.append(Sufixo('mente', ['documente', 'experimente', 'dormente', 'alimente', 'cumprimente', 'movimente'], 3))
    sufixosE.append(Sufixo('quice', [], 4))
    sufixosE.append(Sufixo('riose', [], 4))
    sufixosE.append(Sufixo('cante', ['sindicante'], 4))
    sufixosE.append(Sufixo('edade', [], 4))
    sufixosE.append(Sufixo('ante', ['espante', 'plante', 'gigante', 'elefante', 'adiante', 'possante', 'instante', 'restaurante'], 2))
    sufixosE.append(Sufixo('arde', [], 2))
    sufixosE.append(Sufixo('asse', [], 2))
    sufixosE.append(Sufixo('aste', [], 2))
    sufixosE.append(Sufixo('ense', [], 4))
    sufixosE.append(Sufixo('ente', ['documente', 'continente', 'frequente', 'alimente', 'contente', 'acrescente', 'permanente', 'oriente', 'aparente', 'acidente'], 4))
    sufixosE.append(Sufixo('erde', [], 3))
    sufixosE.append(Sufixo('esse', [], 3))
    sufixosE.append(Sufixo('este', ['faroeste', 'agreste'], 3))
    sufixosE.append(Sufixo('irde', [], 2))
    sufixosE.append(Sufixo('isse', [], 3))
    sufixosE.append(Sufixo('iste', [], 4))
    sufixosE.append(Sufixo('ície', [], 4))
    sufixosE.append(Sufixo('óide', [], 4))
    sufixosE.append(Sufixo('ame', [], 4))
    sufixosE.append(Sufixo('are', ['prepare'], 2))
    sufixosE.append(Sufixo('ate', [], 4))
    sufixosE.append(Sufixo('ere', ['espere'], 3))
    sufixosE.append(Sufixo('ete', [], 4))
    sufixosE.append(Sufixo('ice', ['cúmplice'], 4))
    sufixosE.append(Sufixo('ire', ['adquire'], 3))
    sufixosE.append(Sufixo('ite', [], 4))
    sufixosE.append(Sufixo('ote', [], 4))
    sufixosE.append(Sufixo('ose', [], 4))
    sufixosE.append(Sufixo('que', ['tanque', 'almanaque'], 4))
    sufixosE.append(Sufixo('rre', [], 4))
    sufixosE.append(Sufixo('ue', ['almanaque', 'prossegue'], 3))
    sufixosE.append(Sufixo('fe', [], 3))
    sufixosE.append(Sufixo('me', ['seme', 'informe', 'acalme'], 3))
    sufixosE.append(Sufixo('pe', [], 4))
    sufixosE.append(Sufixo('re', [], 4))
    sufixosE.append(Sufixo('te', ['visite', 'topete', 'medite', 'espete', 'escute', 'aponte', 'alerte', 'tribute', 'liberte', 'adverte', 'comente', 'batente', 'plante', 'espante', 'paste', 'acidente', 'acate', 'pinte', 'continente', 'norte', 'mente', 'junte', 'grande', 'imite', 'dente', 'cante', 'chute', 'horizonte', 'contente'], 4))
    sufixosE.append(Sufixo('e', ['seme', 'almanaque', 'paste'], 3))
    sufixos['e'] = sufixosE
    sufixos['é'] = sufixosE
    sufixos['ê'] = sufixosE

    sufixosI = list()
    sufixosI.append(Sufixo('aríei', [], 2))
    sufixosI.append(Sufixo('ássei', [], 2))
    sufixosI.append(Sufixo('eríei', [], 3))
    sufixosI.append(Sufixo('íssei', [], 3))
    sufixosI.append(Sufixo('árei', [], 3))
    sufixosI.append(Sufixo('arei', [], 2))
    sufixosI.append(Sufixo('ávei', [], 2))
    sufixosI.append(Sufixo('erei', [], 3))
    sufixosI.append(Sufixo('êrei', [], 3))
    sufixosI.append(Sufixo('irei', ['admirei'], 3))
    sufixosI.append(Sufixo('quei', [], 4))
    sufixosI.append(Sufixo('eoi', [], 5))
    sufixosI.append(Sufixo('íei', [], 3))
    sufixosI.append(Sufixo('uei', [], 3))
    sufixosI.append(Sufixo('zei', [], 3))
    sufixosI.append(Sufixo('cei', [], 4))
    sufixosI.append(Sufixo('ai', [], 3))
    sufixosI.append(Sufixo('ei', [], 3))
    sufixosI.append(Sufixo('i', ['ratifi', 'pacifi', 'bucoli', 'repli', 'angari', 'funcionári', 'confi', 'desafi', 'academi', 'colegi', 'biquíni', 'envi', 'alivi'], 4))
    sufixos['i'] = sufixosI
    sufixos['í'] = sufixosI

def removePrefixo(palavra):
    tPalavra = len(palavra)
    for pref in prefixos:
        tPrefixo = len(pref.afixo)
        if (tPalavra - tPrefixo >= 2) and palavra.startswith(pref.afixo) and not palavra.startswith(tuple(pref.excecoes)):
            return palavra[len(pref.afixo):]
    return palavra

def removeSufixo(palavra):
    tPalavra = len(palavra)
    for letra in sufixos.keys():
        if palavra.endswith(letra):
            for suf in sufixos[letra]:
                tSufixo = len(suf.afixo)
                if (tPalavra - tSufixo >= suf.minStem) and palavra.endswith(suf.afixo) and not palavra.endswith(tuple(suf.excecoes)):
                    palavra = palavra[:-len(suf.afixo)]
                    break
    return palavra

def removeExcecoes(palavra):
    tPalavra = len(palavra)

    excecoes = list()
    excecoes.append(Sufixo('alizaç', [], 5))
    excecoes.append(Sufixo('atizaç', [], 5))
    excecoes.append(Sufixo('tizaç', [], 5))
    excecoes.append(Sufixo('izaç', ['organizaç'], 5))
    excecoes.append(Sufixo('aç', ['equaç', 'relaç'], 3))
    excecoes.append(Sufixo('iç', ['eleiç'], 3))
    excecoes.append(Sufixo('ez', [], 2))

    for suf in excecoes:
        tSufixo = len(suf.afixo)
        if (tPalavra - tSufixo >= suf.minStem) and palavra.endswith(suf.afixo) and not palavra.endswith(tuple(suf.excecoes)):
            return palavra[:-len(suf.afixo)]
    return palavra

def stem(palavra):
    initPrefixos()
    initSufixos()

    palavra = palavra.lower()
    palavra = removePrefixo(palavra)
    palavra = removeSufixo(palavra)
    palavra = removeExcecoes(palavra)
    palavra = unicodedata.normalize('NFKD', palavra).encode('ascii','ignore').decode()

    return palavra
