# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 01:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0003_vote_vote_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='choide_id',
            new_name='choice_id',
        ),
    ]
